global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:7080', 'host.docker.internal:7081']
