name: Scrapper CI with Maven

on:
  push:
    branches: [ "main" ]
    paths:
      - 'scrapper/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'scrapper/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn package -pl scrapper -am

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./scrapper/Dockerfile
          push: true
          tags: tinkoff-project/scrapper:latest